package vcenter

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

// VCenterConfig represents the JSON structure used by excel/automation workflows.
// It matches the schema documented in py-vcenter's vcenter_config.json example file.
type VCenterConfig struct {
	VCenter        string `json:"vcenter"`
	Username       string `json:"username"`
	Password       string `json:"password"`
	Datacenter     string `json:"datacenter"`
	Cluster        string `json:"cluster,omitempty"`
	ResourcePool   string `json:"resource_pool,omitempty"`
	StorageCluster string `json:"storage_cluster,omitempty"`
	Datastore      string `json:"datastore,omitempty"`
	Folder         string `json:"folder,omitempty"`
	DomainUser     string `json:"domain_user,omitempty"`
	DomainPassword string `json:"domain_password,omitempty"`
	AdminPassword  string `json:"admin_password,omitempty"`
	Timezone       int    `json:"timezone,omitempty"`
	VerifySSL      bool   `json:"verify_ssl"`
}

// DefaultVCenterConfig returns a filled configuration struct that mirrors the Python example template.
func DefaultVCenterConfig() VCenterConfig {
	return VCenterConfig{
		VCenter:        "vcenter.example.com",
		Username:       "administrator@vsphere.local",
		Password:       "your-password-here",
		Datacenter:     "Datacenter",
		ResourcePool:   "Resources",
		Cluster:        "Compute-Cluster",
		StorageCluster: "VSAN-Cluster-01",
		Datastore:      "",
		Folder:         "Production/Servers",
		DomainUser:     "svc_domainjoin@corp.example.com",
		DomainPassword: "DomainPassword123!",
		AdminPassword:  "LocalAdminPassword123!",
		Timezone:       110,
		VerifySSL:      false,
	}
}

// Validate performs minimal sanity checks before persisting/using the configuration.
func (cfg VCenterConfig) Validate() error {
	if cfg.VCenter == "" {
		return &ConfigurationError{Message: "vcenter is required"}
	}
	if cfg.Username == "" {
		return &ConfigurationError{Message: "username is required"}
	}
	if cfg.Password == "" {
		return &ConfigurationError{Message: "password is required"}
	}
	if cfg.Datacenter == "" {
		return &ConfigurationError{Message: "datacenter is required"}
	}
	if cfg.ResourcePool == "" {
		return &ConfigurationError{Message: "resource_pool is required"}
	}
	if cfg.Cluster == "" && cfg.StorageCluster == "" && cfg.Datastore == "" {
		return &ConfigurationError{Message: "either cluster, storage_cluster or datastore must be specified"}
	}
	if cfg.Timezone < 0 {
		return &ConfigurationError{Message: "timezone must be positive"}
	}
	return nil
}

// Save writes the configuration as JSON to the given file path.
func (cfg VCenterConfig) Save(path string) error {
	if err := cfg.Validate(); err != nil {
		return err
	}
	data, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal config: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}
	return os.WriteFile(path, data, 0o600)
}

// LoadVCenterConfig reads a JSON file and parses it into VCenterConfig.
func LoadVCenterConfig(path string) (VCenterConfig, error) {
	var cfg VCenterConfig
	data, err := os.ReadFile(path)
	if err != nil {
		return cfg, fmt.Errorf("failed to read config: %w", err)
	}
	if err := json.Unmarshal(data, &cfg); err != nil {
		return cfg, fmt.Errorf("failed to parse config: %w", err)
	}
	return cfg, cfg.Validate()
}

// CreateVCenterConfigTemplate writes a human-friendly configuration template with warnings/comments.
func CreateVCenterConfigTemplate(path string) error {
	if _, err := os.Stat(path); err == nil {
		return &ConfigurationError{Message: fmt.Sprintf("refusing to overwrite existing file: %s", path)}
	}

	template := map[string]any{
		"_comment": "Example vCenter configuration file generated by the Go API",
		"_warning": "WARNING: Do NOT store passwords in plaintext JSON files for production!",
		"_production_alternatives": []string{
			"Use environment variables",
			"Use encrypted configuration files",
			"Use enterprise secrets management (Vault, AWS Secrets Manager, etc.)",
			"Prompt for secrets interactively",
		},
	}

	cfg := DefaultVCenterConfig()
	cfgBytes, err := json.Marshal(cfg)
	if err != nil {
		return err
	}

	if err := json.Unmarshal(cfgBytes, &template); err != nil {
		return fmt.Errorf("failed to merge template: %w", err)
	}

	data, err := json.MarshalIndent(template, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal template: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("failed to create directory: %w", err)
	}

	if err := os.WriteFile(path, data, 0o600); err != nil {
		return fmt.Errorf("failed to write template: %w", err)
	}
	return nil
}

// MergeWithDefaults overlays blank fields in cfg with values from defaults (non-destructive).
func (cfg *VCenterConfig) MergeWithDefaults(defaults VCenterConfig) {
	if cfg == nil {
		return
	}
	if cfg.VCenter == "" {
		cfg.VCenter = defaults.VCenter
	}
	if cfg.Username == "" {
		cfg.Username = defaults.Username
	}
	if cfg.Password == "" {
		cfg.Password = defaults.Password
	}
	if cfg.Datacenter == "" {
		cfg.Datacenter = defaults.Datacenter
	}
	if cfg.Cluster == "" {
		cfg.Cluster = defaults.Cluster
	}
	if cfg.StorageCluster == "" {
		cfg.StorageCluster = defaults.StorageCluster
	}
	if cfg.Datastore == "" {
		cfg.Datastore = defaults.Datastore
	}
	if cfg.ResourcePool == "" {
		cfg.ResourcePool = defaults.ResourcePool
	}
	if cfg.Folder == "" {
		cfg.Folder = defaults.Folder
	}
	if cfg.DomainUser == "" {
		cfg.DomainUser = defaults.DomainUser
	}
	if cfg.DomainPassword == "" {
		cfg.DomainPassword = defaults.DomainPassword
	}
	if cfg.AdminPassword == "" {
		cfg.AdminPassword = defaults.AdminPassword
	}
	if cfg.Timezone == 0 {
		cfg.Timezone = defaults.Timezone
	}
}

// MustLoadVCenterConfig is a helper that panics on error. Intended for tests/examples only.
func MustLoadVCenterConfig(path string) VCenterConfig {
	cfg, err := LoadVCenterConfig(path)
	if err != nil {
		panic(err)
	}
	return cfg
}

// EnsureConfigFile ensures that a config exists at path, creating a template if needed.
func EnsureConfigFile(path string) (created bool, err error) {
	if _, err := os.Stat(path); err == nil {
		return false, nil
	} else if !errors.Is(err, os.ErrNotExist) {
		return false, err
	}
	return true, CreateVCenterConfigTemplate(path)
}
